package com.glanci.request.domain.error

enum class AuthError : RootError {
    InvalidToken,
    InsufficientPermissions,
    AppVersionIsBelowRequired,
    ErrorDuringExtractingJwtSecret,
    ErrorDuringCreatingJwtToken,
    OobCodeExpired,
    InvalidOobCode,
    InvalidCredentials,
    InvalidName,
    InvalidEmail,
    InvalidPassword,
    ErrorDuringFetchingUserDataFromAuthProvider,
    ErrorDuringVerifyingOobCodeByAuthProvider,
    UserAlreadyExists,
    SignUpFailed,
    SendingVerificationEmailFailed,
    EmailVerificationFailed,
    EmailNotVerified,
    EmailUpdateRequestFailed,
    EmailUpdateFailed,
    PasswordUpdateFailed,
    PasswordResetRequestFailed,
    PasswordResetFailed,
    UserDeletionFailed,
    InvalidLanguage,

    UserNotFound,
    UserNotFetched,
    UserNotCreated,
    UserNameNotSaved,
    UserEmailNotSaved,
    UserLanguageNotSaved,
    UserSubscriptionNotSaved,
    UserNotDeleted
}