package com.glanci.auth.error

import com.glanci.request.domain.RootError

enum class AuthError : RootError {
    InvalidToken,
    InsufficientPermissions,
    AppVersionIsBelowRequired,
    UserAuthDataIsMissingOrInvalid,
    ErrorDuringExtractingJwtSecret,
    ErrorDuringCreatingJwtToken,
    SignUpFormIsMissingOrInvalid,
    UserCredentialsAreMissingOrInvalid,
    UserIdIsMissing,
    OobCodeIsMissing,
    OobCodeExpired,
    InvalidOobCode,
    InvalidCredentials,
    InvalidName,
    InvalidEmail,
    InvalidPassword,
    ErrorDuringFetchingUserDataFromAuthProvider,
    ErrorDuringVerifyingOobCodeByAuthProvider,
    UserAlreadyExists,
    SignUpFailed,
    SendingVerificationEmailFailed,
    EmailVerificationFailed,
    EmailNotVerified,
    EmailUpdateRequestIsMissingOrInvalid,
    EmailUpdateRequestFailed,
    EmailUpdateFailed,
    PasswordUpdateRequestIsMissingOrInvalid,
    PasswordUpdateFailed,
    EmailIsMissing,
    PasswordResetRequestFailed,
    PasswordResetRequestIsMissingOrInvalid,
    PasswordResetFailed,
    UserDeletionFailed,
    SaveLanguageRequestIsMissingOrInvalid,
    InvalidLanguage,

    UserNotFound,
    UsersNotFound,
    UserNotFetched,
    UsersNotFetched,
    UserNotCreated,
    UserNameNotSaved,
    UserEmailNotSaved,
    UserLanguageNotSaved,
    UserSubscriptionNotSaved,
    UserNotDeleted
}